### ISSUE TITLE
Responsive images on featured collection section.

### ISSUE THREAD

**Issue by kivlov** [Shopify/starter-theme#146] opened 2019-01-30 11:59 UTC
I get an error from the lazysizes package because  it's failing to to pick up a width attribute from `data-src` attribute. 

`{%- assign img_url = image | img_url: '1x1' | replace: '_1x1.', '_{width}x.' -%}`

I cannot figure out were `_{width}x.` is being defined.

![image](https://user-images.githubusercontent.com/6742768/51980205-a7769300-248f-11e9-9a1e-a27a9182ab80.png)
![image](https://user-images.githubusercontent.com/6742768/51980242-bf4e1700-248f-11e9-9f92-f697cca4be02.png)

**Comment by rhandrade** [comment] 2019-02-15 12:08
I found the problem and is not related directly with lazyload js. The problem is in `responsive-image.liquid` file. 

Look for `{%- assign image_widths = image_widths | strip_newlines -%}` line. `strip_newlines` filter should remove newlines from variable `image_widths`, but don't work. I replaced `strip_newlines` for `strip` that remove tabs, blank space and newlines. With that the lazyload script is able to generate and load images.

I think that should be fixed in next commit.

**Comment by kivlov** [comment] 2019-02-15 15:20
Yes, I managed to figure it out a day or two later. I created a pull request #150 with the solution I found
where I replaced `{{ image.width }}` with `{{- image.width -}}`.

**Comment by huguestennier** [comment] 2019-02-27 18:56
Closed via https://github.com/Shopify/starter-theme/pull/150

**Closed by huguestennier** 2019-02-27 18:56 UTC
